# Generated by Django 5.2.16 on 2026-07-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
